<img src="https://github.com/pavlek358/intro-to-eda-and-pandas/blob/main/assets/ga-logo.png?raw=1" style="float: left; margin: 20px; height: 55px">

# Introduction to `pandas`

---

### About
`pandas` is the most popular python package for managing datasets and is used extensively by data scientists.

### Learning Objectives
- Define `pandas` `Series` and `DataFrame` types and their uses.
- Understand the benefit of vectorized dataset operations.
- Read in a dataset with the `pandas` library.


### Notebook Guide
- What is `pandas`, and why are we using it?
- Reading data with `pandas`
- What are vectorized operations and why are they important?
- Conclusions and Takeaways

# Scenario

You're an analyst working for CoolBricks - a new toy company who wants to compete with LEGO by producing their own bricks and sets. To better understand what kind of sets to create and at what price points, you are tasked with analyzing LEGO's catalogue over time.

The data comes from Kaggle: [https://www.kaggle.com/datasets/alexracape/lego-sets-and-prices-over-time](https://www.kaggle.com/datasets/alexracape/lego-sets-and-prices-over-time)

We are going to use `pandas` to read and explore this data.

## What is `pandas`?
---

- Not a black-and-white mammal, it stands for **Pan**el **da**ta **s**ystem
- The most universally used data analysis library for Python (for data small enough to fit in-memory)
- Created by Wes McKinney and Open Sourced by AQR Capital Management, LLC 2009
- Implemented in highly optimized Python/Cython
    - Translation: Even though Python is "slow", `pandas` gives us C-like speeds!
- Basically put Python on the map as a data science language!

## Why use `pandas`?

- `pandas` contains all the functionality we need to explore a dataset including:
    - reading in data
    - joining multiple data sets together
    - calculating descriptive statistics
    - visualization
    - and much more!
- also, `pandas`, is **fast** and can handle large data sets (as we will see)

# Getting started with `pandas`
---

One important aspect of `pandas` is that it introduces specific *types* for working with data. When we read in data, we get a `DataFrame`

In [42]:
import pandas as pd
url = 'https://raw.githubusercontent.com/juanatga/intro-to-eda-and-pandas/main/data/lego.csv'
lego = pd.read_csv(url)

We use the `read_csv` method (more on this later) to read in the data. `pandas` supports many different data sources, but CSV files are one of the most common.

In [43]:
lego

,Set_ID,Name,Year,Theme,Theme_Group,Subtheme,Category,Packaging,Num_Instructions,Availability,Pieces,Minifigures,Owned,Rating,USD_MSRP,Total_Quantity,Current_Price
0,75-1,PreSchool Set,1975,PreSchool,Pre-school,NaN,Normal,{Not specified},0,{Not specified},16.0,NaN,10.0,0.0,NaN,NaN,NaN
1,77-1,PreSchool Set,1975,PreSchool,Pre-school,NaN,Normal,{Not specified},0,{Not specified},20.0,NaN,11.0,0.0,NaN,NaN,NaN
2,077-1,Pre-School Set,1975,Duplo,Pre-school,NaN,Normal,{Not specified},0,{Not specified},21.0,NaN,10.0,0.0,NaN,0.0,NaN
3,78-1,PreSchool Set,1975,PreSchool,Pre-school,NaN,Normal,{Not specified},0,{Not specified},32.0,NaN,8.0,0.0,NaN,NaN,NaN
4,78-3,Basic Set,1975,Samsonite,Vintage,Basic set,Normal,Box,0,{Not specified},330.0,NaN,10.0,0.0,NaN,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14931,854242-1,Creeper Key Chain,2023,Gear,Miscellaneous,Key Chains/Minecraft,Gear,Tag,0,LEGO exclusive,NaN,NaN,2.0,0.0,5.99,NaN,NaN
14932,854243-1,Steve Key Chain,2023,Gear,Miscellaneous,Key Chains/Minecraft,Gear,Tag,0,LEGO exclusive,NaN,NaN,2.0,0.0,5.99,NaN,NaN
14933,854244-1,Piglin Key Chain,2023,Gear,Miscellaneous,Key Chains/Minecraft,Gear,Tag,0,LEGO exclusive,NaN,NaN,2.0,0.0,5.99,NaN,NaN
14934,854245-1,Fennec Shand Key Chain,2023,Gear,Miscellaneous,Key Chains/Star Wars,Gear,Tag,0,LEGO exclusive,NaN,NaN,88.0,0.0,5.99,NaN,NaN
14935,854246-1,Scout Trooper Key Chain,2023,Gear,Miscellaneous,Key Chains/Star Wars,Gear,Tag,0,LEGO exclusive,NaN,NaN,107.0,0.0,5.99,NaN,NaN

We now have a `pandas` object - what is its type?

In [44]:
type(lego)

pandas.core.frame.DataFrame

The entire data set is a `DataFrame`. We can preview it!

In [47]:
lego.head()

,Set_ID,Name,Year,Theme,Theme_Group,Subtheme,Category,Packaging,Num_Instructions,Availability,Pieces,Minifigures,Owned,Rating,USD_MSRP,Total_Quantity,Current_Price
0,75-1,PreSchool Set,1975,PreSchool,Pre-school,NaN,Normal,{Not specified},0,{Not specified},16.0,NaN,10.0,0.0,NaN,NaN,NaN
1,77-1,PreSchool Set,1975,PreSchool,Pre-school,NaN,Normal,{Not specified},0,{Not specified},20.0,NaN,11.0,0.0,NaN,NaN,NaN
2,077-1,Pre-School Set,1975,Duplo,Pre-school,NaN,Normal,{Not specified},0,{Not specified},21.0,NaN,10.0,0.0,NaN,0.0,NaN
3,78-1,PreSchool Set,1975,PreSchool,Pre-school,NaN,Normal,{Not specified},0,{Not specified},32.0,NaN,8.0,0.0,NaN,NaN,NaN
4,78-3,Basic Set,1975,Samsonite,Vintage,Basic set,Normal,Box,0,{Not specified},330.0,NaN,10.0,0.0,NaN,0.0,NaN

How many rows and columns is it?

In [48]:
lego.shape

(14936, 17)

What kind of columns do we have?

In [49]:
lego.columns

Index(['Set_ID', 'Name', 'Year', 'Theme', 'Theme_Group', 'Subtheme',
       'Category', 'Packaging', 'Num_Instructions', 'Availability', 'Pieces',
       'Minifigures', 'Owned', 'Rating', 'USD_MSRP', 'Total_Quantity',
       'Current_Price'],
      dtype='object')

If we need the column names as a list of strings, we can do that

In [56]:
list(lego.columns)

['Set_ID',
 'Name',
 'Year',
 'Theme',
 'Theme_Group',
 'Subtheme',
 'Category',
 'Packaging',
 'Num_Instructions',
 'Availability',
 'Pieces',
 'Minifigures',
 'Owned',
 'Rating',
 'USD_MSRP',
 'Total_Quantity',
 'Current_Price']

Rows and columns are all represented as `pandas` `Series` objects. To select a single column, you can use syntax that looks like accessing Python dictionaries:

In [57]:
lego['Year']

0        1975
1        1975
2        1975
3        1975
4        1975
         ...
14931    2023
14932    2023
14933    2023
14934    2023
14935    2023
Name: Year, Length: 14936, dtype: int64

This is a single column - let's check its type

***Remember:***

* A **`Series`** is a one-dimensional array of values **with an index** (like indices of elements in a list)
* A **`DataFrame`** is a two-dimensional array of values **with both a row and column index**
* It turns out - each column of a `DataFrame` is actually a `Series`!

We can check this row index, which by default is the numbers 0 to length-1:

We can also check what data types `pandas` has inferred for our columns

In `pandas`, "object" means it wasn't obvious what type it should be. Often these are text columns but not always.

We can also get a more complete picture of the data with `.info`

## Vectorized operations
---

Why bother with `DataFrame` and `Series` object when we could use Python lists and dictionaries?

`pandas` uses `numpy` arrays under the hood, which can perform operations **on an entire collection of values** rather than looping through the values individually.

Let's see a basic example.

We'll square the first 100,000 integers: first with a `for` loop, then as a `pandas` `Series` and compare timings.

*(we can use Jupyter's `%%timeit` command to time how long a cell takes to run)*

Option 1: a `for` loop

Option 2: `pandas` `Series`

# Conclusions and Takeaways
---

- `pandas` is the most popular data analysis library in the Python ecosystem
- `pandas` introduces the `Series` and `DataFrame` types to make manipulating data easier
- `pandas` uses vectorized operations to manipulate entire columns at once